# This is a basic workflow to help you get started with Actions

name: Jfrog integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v1.1.1
        env:
          JF_ARTIFACTORY_1: ${{ secrets.JFROG_TOKEN }}
      - name: Relay to JFrog Build
        run: 
          jfrog rt dl artifacts/
          jfrog rt u aether artifacts/
          jfrog rt bp


  
