# This is a basic workflow to help you get started with Actions

name: Jfrog integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: test
        shell: bash
        env:
          JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
        run: echo "$JFROG_TOKEN"
        
        
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v1.1.1
        env:
          JF_ARTIFACTORY_1: ${{ secrets.JFROG_TOKEN }}
      - name: Relay to JFrog Build
        run: jfrog rt bp
          


  
